name: Echo Input Workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Enter a message to echo"
        required: true
        default: "Hello from workflow_dispatch!"
        type: string
  workflow_call:
    inputs:
      message:
        description: "Message from caller workflow"
        required: true
        type: string
jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - name: Echo Input Parameter
      run: echo "Input message: $inputs.message"
